//****** LOGIN  ********//
export const GET_GAMESEDITIONS = "GET_GAMESEDITIONS";
export const CREATE_GAMESEDITIONS = "CREATE_GAMESEDITIONS";
export const UPDATE_GAMESEDITIONS = "CREATE_GAMESEDITIONS";
export const DELETE_GAMESEDITIONS = "DELETE_GAMESEDITIONS";