//****** LOGIN  ********//
export const GET_FUNCTIONALAREAS = "GET_FUNCTIONALAREAS";
export const CREATE_FUNCTIONALAREAS = "CREATE_FUNCTIONALAREAS";
export const UPDATE_FUNCTIONALAREAS = "UPDATE_FUNCTIONALAREAS";
export const DELETE_FUNCTIONALAREAS = "DELETE_FUNCTIONALAREAS";